Repository davidcole1340/ext-php-rs, pull requests merged in 2025-07, with the labels that each got.

#459 fix(cargo-php): get_ext_dir()/get_php_ini(): stdout noise tolerance
  crates/cli/src/lib.rs
Labels: bug

#457 fix(FunctionBuilder): return type '?void' is now just 'void'
  src/builders/function.rs
Labels: bug, stubs

#491 fix: support defaults for calls with named arguments
  src/args.rs
  tests/src/integration/defaults/defaults.php
  tests/src/integration/defaults/mod.rs
Labels: bug, regression
